name = "NAME_GENERATOR_MODULE"
description = "Generates character names for games"
version = "0.1.3"
author = "Yakachi"
github = "Gelbpunkt/NAME_GENERATOR_MODULE"
bot_type = "Nadybot"
bot_version = "^6.0.0-alpha.1"

[requires]
ext-pcre = "*"
